branches:
  only:
    - staging
    - trying
    - master
dist: trusty
sudo: true
language: rust
matrix:
  include:
    - rust: stable
      os: linux
      env: CHECK=check
    - rust: beta
      os: linux
      env: CHECK=clippy
    - rust: nightly
      os: linux
      env: CHECK=clippy
    - rust: stable
      os: osx
      env: CHECK=check
    - rust: beta
      os: osx
      env: CHECK=clippy
    - rust: nightly
      os: osx
      env: CHECK=clippy
  allow_failures:
    - rust: beta
    - rust: nightly
before_install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get install -y libopenal-dev && export PKG_CONFIG_ALLOW_SYSTEM_CFLAGS=1; else brew install openal-soft && export PKG_CONFIG_PATH=/usr/local/opt/openal-soft/lib/pkgconfig; fi
install:
  - rustup component add rustfmt-preview
  - if [ "$CHECK" = "clippy" ]; then rustup component add clippy-preview && cargo clippy -V; fi
  - cargo fmt -v --version
script:
  - cargo $CHECK -vv --tests
  - cargo build -vv
  - cargo doc -vv
  - cargo test -vv
  - cargo fmt -- --check -v
