branches:
  only:
    - staging
    - trying
    - master
environment:
  matrix:
    - CHANNEL: stable
      CHECK: check
    - CHANNEL: beta
      CHECK: check
    - CHANNEL: nightly
      CHECK: clippy
matrix:
  allow_failures:
    - CHANNEL: beta
    - CHANNEL: nightly
install:
  - SET PATH=%USERPROFILE%\.cargo\bin;%PATH%
  - ps: Start-FileDownload "https://static.rust-lang.org/rustup/dist/x86_64-pc-windows-msvc/rustup-init.exe"
  - rustup-init.exe -y --no-modify-path --default-host x86_64-pc-windows-msvc --default-toolchain %CHANNEL%
  - rustup component add rustfmt-preview
  - IF "%CHANNEL%"=="nightly" rustup component add clippy-preview && cargo clippy -V
  - rustup -vV
  - rustc -vV
  - cargo -vV
  - cargo fmt -v --version
build_script:
  - cargo %CHECK% -vv --tests
  - cargo build -vv
  - cargo doc -vv
test_script:
  - cargo test -vv
  - cargo fmt -- --check -v
